language: php
php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer update --prefer-source; composer install --dev --prefer-source;

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml ./tests/
  - ./vendor/bin/phpcs --standard=PSR2 ./module/ ./tests/
  
after_script:
  - php vendor/bin/coveralls -v

notifications:
  irc: false
  email: false