<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */


$modules = array(
        'DoctrineModule',
        'DoctrineORMModule',
        'ZfcBase',
        'ZfcUser',
        'ZfcUserDoctrineORM',
        'ZfcRbac',
        'ZfcTwig',
        
        'Application',
        'Auth',
        'Game',
        'Admin',
    );

if (IS_DEV) {
    $modules[] = 'ZendDeveloperTools';
    //$modules[] = 'OcraServiceManager';
    //$modules[] = 'BjyProfiler',
    $modules[] = 'DoctrineDataFixtureModule';
}

return array(
    'modules' => $modules,
    
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        )
    ),
    
);
