<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
!defined('IS_DEV') ? DEFINE('IS_DEV', true) : false;
return array(
    'modules' => array(
        'DoctrineModule',
        'DoctrineORMModule',
        'ZfcBase',
        'ZfcUser',
        'ZfcUserDoctrineORM',
        'ZfcRbac',
        'ZfcTwig',
        'ZendDeveloperTools',
        //'OcraServiceManager',
        //'BjyProfiler',
        'Application',
        'Auth',
        'Admin',
        'Game',

        'DoctrineDataFixtureModule',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        )
    ),
    'service_manager' => array(
        'aliases' => array(
            'Zend\Authentication\AuthenticationService' => 'zfcuser_auth_service'
        ),
        'factories' => array(
            'doctrine.cache.app_memcache' => function ($sm) {
                    $cache = new \Doctrine\Common\Cache\MemcacheCache();
                    $memcache = new \Memcache();
                    $memcache->connect('localhost', 11211);
                    $cache->setMemcache($memcache);
                    return $cache;
                },
        ),
    ),
);
